### PR TITLE
block bundler < 1.6.5

### PR DESCRIPTION
**Pull request by steved**

### CODE REVIEW

**Comment by alanhogan** [comment]
+1

**Comment by alanhogan** [comment]
@steved If you still want to champion this PR, you may want to rebase off master to fix tests

**Comment by steved** [comment]
Sure, done. Plus a test (:fireworks:). Mind letting me know if you deploy?

**Comment by alanhogan** [comment]
Nice.

If you wouldn't mind a quick +1 on the tiny PRs I made to this repo…? then maybe i'll find a deploy buddy for this. not sure protocol to deploy this (I’m new)

**Comment by steved** [comment]
Yep. Ping me flowdock and we'll can chat.

**Pull request merged**
