### PR TITLE
Upgrade to ruby 2.3.0

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @mphoratiu @grosser @steved 

### Steps to merge
* [x] Ruby 2.3.0 installed on the servers
* [ ] :+1: from the team

### Risks
* Low

### CODE REVIEW

**Comment by mphoratiu** [comment]
:+1: from Ops

**Comment by grosser** [comment]
:+1:

**Comment by pschambacher** [comment]
Waiting for Steven

**Comment by steved** [comment]
+1

**Pull request merged**
