### PR TITLE
Upgrade Rails to 4.2

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @steved @grosser 
### Steps to reproduce

How do we actually test this application outside of the tests? I was able to start the server locally but on master or this branch I get an error quite quickly since I do not have any certificate.
### Steps to merge
- [ ] :+1: from the team
### Risks
- Medium: Lots of gem upgraded, should be tested before merge

### CODE REVIEW

**Comment by grosser** [comment]
:+1: :heart: upgrade all the things :D

**Comment by steved** [comment]
There's no docker image so everyone always makes PRs to disable SSL in dev. It was set up on boxen properly, but I'm guessing you don't use that. Either make a container, or merge #10.

**Comment by pschambacher** [comment]
I'll cherry-pick that branch to test :)

**Comment by grosser** [comment]
going straight to 5.0

**Pull request closed without merging**
